version: '3'

services:
  db.internal:
    image: mysql:5.7
    container_name: db
    environment:
       MYSQL_DATABASE: 'db'
       MYSQL_ROOT_PASSWORD: 'password'
    volumes:
     - "dev-volume:/var/lib/mysql"
    networks:
      - main_network

  s3.docker:
    image: minio/minio
    container_name: s3
    #command:
    #  gateway gcs
    volumes:
      - "dev-volume:/data"
      - ./s3/credentials.json:/credentials.json
    command: server /data
    environment:
      # use only with google cloud storage (gcs) gateway
      #GOOGLE_APPLICATION_CREDENTIALS: '/credentials.json'
      MINIO_ACCESS_KEY: 'admin'
      MINIO_SECRET_KEY: 'password'
    networks:
      - main_network
    depends_on:
      - db.internal
      - rabbit.internal

  webapp.docker:
    container_name: webapp
    build: .
    command: bash -c "python manage.py migrate && gunicorn apiGateway.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - ./apiGateway/:/usr/src/apiGateway
    depends_on:
      - db.internal
    networks:
      - main_network

  rabbit.internal:
    image: rabbitmq:3.7.18-management
    # below image used if no management is needed
    #image: rabbitmq:latest
    container_name: rabbit
    networks: 
      - main_network
    #volumes:
    #  - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbit
    ports:
      - 5672:5672
      # below ports are only needed if management panel needs to be enabled
      - 15672:15672

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
      - 3306:3306
      - 9000:9000
    volumes:
        - ./config/nginx/conf.d:/etc/nginx/conf.d
        - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - webapp.docker
      - db.internal
    networks:
      - main_network

networks:
  main_network:
    driver: bridge

volumes:
  dev-volume:
